name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Use Node.js 14 or higher

      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform

      - name: Terraform Init
        run: terraform init
        #working-directory: .

      - name: Terraform Plan
        run: terraform plan
        #working-directory: .

      - name: Terraform Apply
        run: terraform apply -auto-approve
        #working-directory: .
