name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy
    runs-on: self-hosted

    steps:

      #- name: Checkout Repository
      #  uses: actions/checkout@v3

      #- name: Setup Node.js
      #  uses: actions/setup-node@v3
      #  with:
      #   node-version: '14'  # Use Node.js 14 or higher

      - name: Terraform Init
        run: terraform init
        #working-directory: .

      - name: Terraform Plan
        run: terraform plan
        #working-directory: .

      - name: Terraform Apply
        run: terraform apply --auto-approve
        #working-directory: .
      
      - name: Terraform Destroy
        run: terraform destroy
